// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {PacketCapture} from '../models';

export function StartNetworkCapture(arg1:PacketCapture.NetworkInterface):Promise<void>;
