// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartNetworkCapture(arg1) {
  return window['go']['PacketCapture']['NetworkInterface']['StartNetworkCapture'](arg1);
}
